pin zodb to the 3.8.x series for now, as 3.9 breaks the test setup resulting in {{{ AttributeError: 'DemoStorage' object has no attribute '_tid' }}} this way any real issues don't get masked and can be fixed first...